# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickApp_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickApp_iOS
    pod 'GoogleWebRTC', '1.1.26379'
    pod 'Socket.IO-Client-Swift', '~> 12.0.0'
    pod 'SVProgressHUD'
    pod 'ReachabilitySwift'
    pod 'Fabric'
    pod 'Crashlytics'
    
  target 'QuickApp_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickApp_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
