# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickApp_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickApp_iOS
    pod 'EnxRTCiOS'
    pod 'Socket.IO-Client-Swift', '~> 16.1.0'
    pod 'SVProgressHUD'
    pod 'ReachabilitySwift'
    pod 'Fabric'
    pod 'Crashlytics'
    
  target 'QuickApp_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickApp_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  post_install do |installer|
            installer.generated_projects.each do |project|
                  project.targets.each do |target|
                      target.build_configurations.each do |config|
                          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                       end
                  end
           end
        end
end
